name: Publish to Nuget
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./
      - name: Publish
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: csharp-htk.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}